server:
  port: 8080

spring:
  application:
    name: ACCOUNTS

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: "org.postgresql.Driver"
    username: admin
    password: admin
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: ${spring.application.name}
    description: "CureMap Accounts Service Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

aws:
  access-key-id: AKIARZYETDP3C6EGRZW3
  secret-access-key: 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
  region: us-east-1
  s3:
    bucket-name: curemap-vault
    endpoint:
    path-style-access: true

#  AKIARZYETDP3C6EGRZW3
# z8eDQuL9l17INhExCGIC97MjWLj4TEkeaveej/WG
files:
  acceptedImages:
    - ".jpeg"
    - ".jpg"
    - ".png"
  acceptedAudios:
    - ".wav"    # Uncompressed, high quality
    - ".aiff"   # Uncompressed, high quality
    - ".mp3"    # Most common compressed format
    - ".m4a"    # Apple's preferred format
    - ".ogg"    # Open source alternative
    - ".flac"   # Lossless compression
    - ".aac"    # Good quality at lower bitrates
  fileLimits:
    maxImageSizeMB: 5_000_000    # 10MB per image
    maxAudioSizeMB: 50_000_000    # 50MB per audio file

keycloak:
  auth-server-url: http://localhost:8090
  realm: curemap
  client-id: curemap_authentication_app
  client-secret: e8rmnM0WYF87HibrGmYCUzgPsAFG3f9T
  admin-username: admin
  admin-password: admin
